/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dominik Šuráni
 */
public class Aplikacia extends javax.swing.JFrame {

    /**
     * Creates new form Aplikacia
     */
    public Aplikacia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AplikaciaOdhlasitSa = new javax.swing.JButton();
        AplikaciaSkladOvocia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkladOvocia");

        AplikaciaOdhlasitSa.setBackground(new java.awt.Color(0, 0, 0));
        AplikaciaOdhlasitSa.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        AplikaciaOdhlasitSa.setForeground(new java.awt.Color(255, 0, 0));
        AplikaciaOdhlasitSa.setText("Odhlasit sa");
        AplikaciaOdhlasitSa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AplikaciaOdhlasitSaActionPerformed(evt);
            }
        });

        AplikaciaSkladOvocia.setEditable(false);
        AplikaciaSkladOvocia.setBackground(new java.awt.Color(0, 150, 0));
        AplikaciaSkladOvocia.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        AplikaciaSkladOvocia.setForeground(new java.awt.Color(150, 0, 0));
        AplikaciaSkladOvocia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AplikaciaSkladOvocia.setText("Sklad ovocia");
        AplikaciaSkladOvocia.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(AplikaciaOdhlasitSa)
                .addGap(26, 26, 26)
                .addComponent(AplikaciaSkladOvocia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AplikaciaOdhlasitSa)
                    .addComponent(AplikaciaSkladOvocia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 373, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AplikaciaOdhlasitSaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AplikaciaOdhlasitSaActionPerformed
        Login log = new Login();
        log.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AplikaciaOdhlasitSaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplikacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplikacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplikacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplikacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplikacia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AplikaciaOdhlasitSa;
    private javax.swing.JTextField AplikaciaSkladOvocia;
    // End of variables declaration//GEN-END:variables
}
