
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dominik Šuráni
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginMeno = new javax.swing.JTextField();
        LoginHeslo = new javax.swing.JTextField();
        LoginPrihlasenie = new javax.swing.JTextField();
        LoginPrihlasit = new javax.swing.JButton();
        LoginRegistrovat = new javax.swing.JButton();
        LoginHesloText = new javax.swing.JPasswordField();
        LoginMenoText = new javax.swing.JTextField();
        LoginSkladOvocia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkladOvocia-Prihlasenie");
        setBackground(new java.awt.Color(128, 0, 0));

        LoginMeno.setEditable(false);
        LoginMeno.setBackground(new java.awt.Color(125, 0, 0));
        LoginMeno.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        LoginMeno.setForeground(new java.awt.Color(0, 0, 0));
        LoginMeno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginMeno.setText("Meno");
        LoginMeno.setToolTipText("");
        LoginMeno.setCaretColor(new java.awt.Color(128, 0, 0));
        LoginMeno.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        LoginMeno.setFocusable(false);

        LoginHeslo.setEditable(false);
        LoginHeslo.setBackground(new java.awt.Color(125, 0, 0));
        LoginHeslo.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        LoginHeslo.setForeground(new java.awt.Color(0, 0, 0));
        LoginHeslo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginHeslo.setText("Heslo");
        LoginHeslo.setToolTipText("");
        LoginHeslo.setCaretColor(new java.awt.Color(128, 0, 0));
        LoginHeslo.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        LoginHeslo.setFocusable(false);

        LoginPrihlasenie.setEditable(false);
        LoginPrihlasenie.setBackground(new java.awt.Color(125, 0, 0));
        LoginPrihlasenie.setFont(new java.awt.Font("Algerian", 1, 25)); // NOI18N
        LoginPrihlasenie.setForeground(new java.awt.Color(0, 0, 0));
        LoginPrihlasenie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginPrihlasenie.setText("Prihlasenie");
        LoginPrihlasenie.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        LoginPrihlasenie.setFocusable(false);

        LoginPrihlasit.setBackground(new java.awt.Color(0, 0, 200));
        LoginPrihlasit.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LoginPrihlasit.setForeground(new java.awt.Color(0, 0, 0));
        LoginPrihlasit.setText("Prihlasit");
        LoginPrihlasit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPrihlasitActionPerformed(evt);
            }
        });

        LoginRegistrovat.setBackground(new java.awt.Color(0, 175, 0));
        LoginRegistrovat.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LoginRegistrovat.setForeground(new java.awt.Color(0, 0, 0));
        LoginRegistrovat.setText("Registrovat");
        LoginRegistrovat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginRegistrovatActionPerformed(evt);
            }
        });

        LoginHesloText.setBackground(new java.awt.Color(125, 0, 0));
        LoginHesloText.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        LoginHesloText.setForeground(new java.awt.Color(255, 255, 255));
        LoginHesloText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LoginHesloText.setToolTipText("ZadajHeslo");

        LoginMenoText.setBackground(new java.awt.Color(125, 0, 0));
        LoginMenoText.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        LoginMenoText.setForeground(new java.awt.Color(255, 255, 255));
        LoginMenoText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LoginMenoText.setToolTipText("ZadajMeno");
        LoginMenoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginMenoTextActionPerformed(evt);
            }
        });

        LoginSkladOvocia.setEditable(false);
        LoginSkladOvocia.setBackground(new java.awt.Color(0, 150, 0));
        LoginSkladOvocia.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        LoginSkladOvocia.setForeground(new java.awt.Color(150, 0, 0));
        LoginSkladOvocia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LoginSkladOvocia.setText("SkladOvocia");
        LoginSkladOvocia.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LoginMeno, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LoginMenoText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LoginHeslo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(LoginPrihlasit)
                                        .addGap(18, 18, 18)
                                        .addComponent(LoginRegistrovat)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(LoginHesloText)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(LoginSkladOvocia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(LoginPrihlasenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginSkladOvocia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginPrihlasenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginMeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginMenoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginHeslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoginHesloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoginPrihlasit)
                    .addComponent(LoginRegistrovat))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginPrihlasitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPrihlasitActionPerformed

        if((LoginMenoText.getText().equals("SkladOvocia")) && (LoginHesloText.getText().equals("Dominik27462003"))){
            Aplikacia app = new Aplikacia();
            app.setVisible(true);
            this.setVisible(false);
        } else{
            LoginMenoText.setText("Nesprávne meno");
            LoginMenoText.setBackground(Color.black);
            LoginHesloText.setText("Nespravne heslo");
            LoginHesloText.setBackground(Color.black);
        }
            
    }//GEN-LAST:event_LoginPrihlasitActionPerformed

    private void LoginRegistrovatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginRegistrovatActionPerformed
        Registracia reg = new Registracia();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LoginRegistrovatActionPerformed

    private void LoginMenoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginMenoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginMenoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LoginHeslo;
    private javax.swing.JPasswordField LoginHesloText;
    private javax.swing.JTextField LoginMeno;
    private javax.swing.JTextField LoginMenoText;
    private javax.swing.JTextField LoginPrihlasenie;
    private javax.swing.JButton LoginPrihlasit;
    private javax.swing.JButton LoginRegistrovat;
    private javax.swing.JTextField LoginSkladOvocia;
    // End of variables declaration//GEN-END:variables
}
