
import com.sun.jdi.connect.spi.Connection;
import java.awt.Color;
import java.beans.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dominik Šuráni
 */
public class Registracia extends javax.swing.JFrame {

    /**
     * Creates new form Registracia
     */
    public Registracia() {
        initComponents();
    }
    
    public boolean KontrolaHesla(String Heslo){
        int PocetMPismen = 0;
        int PocetVPismen = 0;
        int PocetCislic = 0;
        
        for(int i=0; i<Heslo.length(); i++){
            char znak = Heslo.charAt(i);
            if(Character.isDigit(znak)){
                PocetCislic++;
            }else if(Character.isLowerCase(znak)){
                PocetMPismen++;
            }else if(Character.isUpperCase(znak)){
                PocetVPismen++;
            }
        }
        if(PocetMPismen==0 && PocetVPismen==0 && PocetCislic==0){
            return false;
        } else{
            return true;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistraciaRegistracia = new javax.swing.JTextField();
        RegistraciaMeno = new javax.swing.JTextField();
        RegistraciaHeslo = new javax.swing.JTextField();
        RegistraciaRegistrovat = new javax.swing.JButton();
        RegistraciaMenoText = new javax.swing.JTextField();
        RegistraciaPriezvisko = new javax.swing.JTextField();
        RegistraciaEMail = new javax.swing.JTextField();
        RegistraciaBydlisko = new javax.swing.JTextField();
        RegistraciaHesloText = new javax.swing.JPasswordField();
        RegistraciaPriezviskoText = new javax.swing.JTextField();
        RegistraciaBydliskoText = new javax.swing.JTextField();
        RegistraciaEMailText = new javax.swing.JTextField();
        RegistraciaSpat = new javax.swing.JButton();
        RegistraciaSkladOvocia = new javax.swing.JTextField();
        MenoError = new javax.swing.JLabel();
        HesloError = new javax.swing.JLabel();
        PriezviskoError = new javax.swing.JLabel();
        EmailError = new javax.swing.JLabel();
        BydliskoError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SkladOvocia-Registracia");
        setBackground(new java.awt.Color(0, 0, 0));

        RegistraciaRegistracia.setEditable(false);
        RegistraciaRegistracia.setBackground(new java.awt.Color(0, 128, 0));
        RegistraciaRegistracia.setFont(new java.awt.Font("Algerian", 1, 25)); // NOI18N
        RegistraciaRegistracia.setForeground(new java.awt.Color(0, 0, 0));
        RegistraciaRegistracia.setText("Registracia");
        RegistraciaRegistracia.setToolTipText("");
        RegistraciaRegistracia.setDisabledTextColor(new java.awt.Color(0, 255, 0));
        RegistraciaRegistracia.setFocusable(false);

        RegistraciaMeno.setEditable(false);
        RegistraciaMeno.setBackground(new java.awt.Color(0, 128, 0));
        RegistraciaMeno.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        RegistraciaMeno.setForeground(new java.awt.Color(0, 0, 0));
        RegistraciaMeno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RegistraciaMeno.setText("Meno(Prihlasovacie)");
        RegistraciaMeno.setToolTipText("");
        RegistraciaMeno.setFocusable(false);
        RegistraciaMeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraciaMenoActionPerformed(evt);
            }
        });

        RegistraciaHeslo.setEditable(false);
        RegistraciaHeslo.setBackground(new java.awt.Color(0, 128, 0));
        RegistraciaHeslo.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        RegistraciaHeslo.setForeground(new java.awt.Color(0, 0, 0));
        RegistraciaHeslo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RegistraciaHeslo.setText("Heslo");
        RegistraciaHeslo.setToolTipText("");
        RegistraciaHeslo.setFocusable(false);

        RegistraciaRegistrovat.setBackground(new java.awt.Color(0, 128, 0));
        RegistraciaRegistrovat.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        RegistraciaRegistrovat.setForeground(new java.awt.Color(0, 0, 0));
        RegistraciaRegistrovat.setText("Registrovat!");
        RegistraciaRegistrovat.setToolTipText("");
        RegistraciaRegistrovat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraciaRegistrovatActionPerformed(evt);
            }
        });

        RegistraciaMenoText.setBackground(new java.awt.Color(0, 175, 0));
        RegistraciaMenoText.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        RegistraciaMenoText.setForeground(new java.awt.Color(255, 255, 255));
        RegistraciaMenoText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RegistraciaMenoText.setToolTipText("Meno");
        RegistraciaMenoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraciaMenoTextActionPerformed(evt);
            }
        });

        RegistraciaPriezvisko.setEditable(false);
        RegistraciaPriezvisko.setBackground(new java.awt.Color(0, 128, 0));
        RegistraciaPriezvisko.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        RegistraciaPriezvisko.setForeground(new java.awt.Color(0, 0, 0));
        RegistraciaPriezvisko.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RegistraciaPriezvisko.setText("Priezvisko");
        RegistraciaPriezvisko.setToolTipText("");
        RegistraciaPriezvisko.setFocusable(false);
        RegistraciaPriezvisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraciaPriezviskoActionPerformed(evt);
            }
        });

        RegistraciaEMail.setEditable(false);
        RegistraciaEMail.setBackground(new java.awt.Color(0, 128, 0));
        RegistraciaEMail.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        RegistraciaEMail.setForeground(new java.awt.Color(0, 0, 0));
        RegistraciaEMail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RegistraciaEMail.setText("E-mail");
        RegistraciaEMail.setToolTipText("");
        RegistraciaEMail.setFocusable(false);
        RegistraciaEMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraciaEMailActionPerformed(evt);
            }
        });

        RegistraciaBydlisko.setEditable(false);
        RegistraciaBydlisko.setBackground(new java.awt.Color(0, 128, 0));
        RegistraciaBydlisko.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        RegistraciaBydlisko.setForeground(new java.awt.Color(0, 0, 0));
        RegistraciaBydlisko.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RegistraciaBydlisko.setText("Bydlisko");
        RegistraciaBydlisko.setToolTipText("");
        RegistraciaBydlisko.setFocusable(false);
        RegistraciaBydlisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraciaBydliskoActionPerformed(evt);
            }
        });

        RegistraciaHesloText.setBackground(new java.awt.Color(0, 175, 0));
        RegistraciaHesloText.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        RegistraciaHesloText.setForeground(new java.awt.Color(255, 255, 255));
        RegistraciaHesloText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RegistraciaHesloText.setToolTipText("Heslo");
        RegistraciaHesloText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraciaHesloTextActionPerformed(evt);
            }
        });

        RegistraciaPriezviskoText.setBackground(new java.awt.Color(0, 175, 0));
        RegistraciaPriezviskoText.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        RegistraciaPriezviskoText.setForeground(new java.awt.Color(255, 255, 255));
        RegistraciaPriezviskoText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RegistraciaPriezviskoText.setToolTipText("Priezvisko");

        RegistraciaBydliskoText.setBackground(new java.awt.Color(0, 175, 0));
        RegistraciaBydliskoText.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        RegistraciaBydliskoText.setForeground(new java.awt.Color(255, 255, 255));
        RegistraciaBydliskoText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RegistraciaBydliskoText.setToolTipText("Bydlisko");

        RegistraciaEMailText.setBackground(new java.awt.Color(0, 175, 0));
        RegistraciaEMailText.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        RegistraciaEMailText.setForeground(new java.awt.Color(255, 255, 255));
        RegistraciaEMailText.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        RegistraciaEMailText.setToolTipText("E-mail");

        RegistraciaSpat.setBackground(new java.awt.Color(0, 175, 0));
        RegistraciaSpat.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        RegistraciaSpat.setForeground(new java.awt.Color(0, 0, 0));
        RegistraciaSpat.setText("Spat!");
        RegistraciaSpat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraciaSpatActionPerformed(evt);
            }
        });

        RegistraciaSkladOvocia.setEditable(false);
        RegistraciaSkladOvocia.setBackground(new java.awt.Color(0, 150, 0));
        RegistraciaSkladOvocia.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        RegistraciaSkladOvocia.setForeground(new java.awt.Color(150, 0, 0));
        RegistraciaSkladOvocia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        RegistraciaSkladOvocia.setText("SkladOvocia");
        RegistraciaSkladOvocia.setFocusable(false);
        RegistraciaSkladOvocia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistraciaSkladOvociaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(RegistraciaSpat, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(RegistraciaSkladOvocia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RegistraciaBydlisko, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RegistraciaBydliskoText))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RegistraciaEMail, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RegistraciaEMailText, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RegistraciaPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RegistraciaPriezviskoText, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RegistraciaMeno)
                                    .addComponent(RegistraciaHeslo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegistraciaRegistracia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(RegistraciaHesloText, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                                        .addComponent(RegistraciaMenoText)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MenoError)
                            .addComponent(PriezviskoError)
                            .addComponent(EmailError)
                            .addComponent(BydliskoError)
                            .addComponent(HesloError, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(RegistraciaRegistrovat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegistraciaSpat)
                    .addComponent(RegistraciaSkladOvocia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistraciaRegistracia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegistraciaMeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegistraciaHeslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegistraciaHesloText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegistraciaPriezvisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegistraciaPriezviskoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PriezviskoError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegistraciaEMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegistraciaEMailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegistraciaBydlisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegistraciaBydliskoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BydliskoError)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegistraciaMenoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MenoError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HesloError, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistraciaRegistrovat)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistraciaMenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraciaMenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistraciaMenoActionPerformed

    private void RegistraciaPriezviskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraciaPriezviskoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistraciaPriezviskoActionPerformed

    private void RegistraciaEMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraciaEMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistraciaEMailActionPerformed

    private void RegistraciaBydliskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraciaBydliskoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistraciaBydliskoActionPerformed

    private void RegistraciaRegistrovatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraciaRegistrovatActionPerformed
        int PocetChyb = 0;
        
        //Obsah pola
        if(RegistraciaMenoText.getText().equals("")){
            MenoError.setText("Meno je povinny udaj!");
            MenoError.setBackground(Color.red);
            PocetChyb++;
        } else {
            MenoError.setText("");
            MenoError.setBackground(Color.white);
        }
        if(RegistraciaPriezviskoText.getText().equals("")){
            PriezviskoError.setText("Priezvisko je povinny udaj!");
            PriezviskoError.setBackground(Color.red);
            PocetChyb++;
        } else {
            PriezviskoError.setText("");
            PriezviskoError.setBackground(Color.white);
        }
        if(RegistraciaHesloText.getText().equals("")){
            HesloError.setText("Heslo je povinny udaj!");
            HesloError.setBackground(Color.red);
            PocetChyb++;
        } else if(RegistraciaHesloText.getText().length()<8){
            BydliskoError.setText("minimalny pocet znakov je 8!");
            BydliskoError.setBackground(Color.red);
            PocetChyb++;
        } else if(!KontrolaHesla(RegistraciaHesloText.getText())){
            HesloError.setText("Heslo nie je bezpecne!");
            HesloError.setBackground(Color.red);
        }else {
            HesloError.setText("");
            HesloError.setBackground(Color.white);
        }
        if(RegistraciaEMailText.getText().equals("")){
            EmailError.setText("Email je povinny udaj!");
            EmailError.setBackground(Color.red);
            PocetChyb++;
        } else {
            EmailError.setText("");
            EmailError.setBackground(Color.white);
        }
        if(RegistraciaBydliskoText.getText().equals("")){
            BydliskoError.setText("Bydlisko je povinny udaj!");
            BydliskoError.setBackground(Color.red);
            PocetChyb++;
        } else {
            BydliskoError.setText("");
            BydliskoError.setBackground(Color.white);
        }
        
        if(RegistraciaEMailText.getText().contains("@")){
            EmailError.setText("");
            EmailError.setBackground(Color.white);
        } else{
            EmailError.setText("Emal musi obsahovat @!");
            EmailError.setBackground(Color.red);
            PocetChyb++;
        }
        
        if(PocetChyb==0){
            try {
                Connection conn = null;
        
                String dbURL = "jdbc:postgresql://localhost:8080/SkladOvocia";
                //String dbURL = "jdbc:postgresql://localhost/projectPRO";
                String user = "SkladOvocia";
                String pass = "Dominik27462003";

                conn = DriverManager.getConnection(dbURL, user, pass);
                if (conn != null) {
                    System.out.println("Pripojene k databaze!");
                    
                    String query = "SELECT password FROM t_user WHERE username = '"+username+"';";

                    Statement st = conn.createStatement();
                    ResultSet rs = st.executeQuery(query);

                    if (rs.next()) {
                        passwordDB = rs.getString("password");
                        System.out.println(passwordDB+" "+password);
                    } else {
                        System.out.println("Pouzivatel neexistuje!");
                    }
                }
            } catch(SQLException ex) {
                System.out.println("Nemozno sa pripojit k databaze!");
                System.out.println("ERROR: "+ex .getMessage());
            }
        
            Aplikacia app = new Aplikacia();
            app.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_RegistraciaRegistrovatActionPerformed
    }
    
    private void RegistraciaHesloTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraciaHesloTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistraciaHesloTextActionPerformed

    private void RegistraciaSpatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraciaSpatActionPerformed
        Login log = new Login();
        log.setVisible(true);
        this.setVisible(false);    }//GEN-LAST:event_RegistraciaSpatActionPerformed

    private void RegistraciaSkladOvociaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraciaSkladOvociaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistraciaSkladOvociaActionPerformed

    private void RegistraciaMenoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistraciaMenoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistraciaMenoTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registracia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registracia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registracia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registracia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registracia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BydliskoError;
    private javax.swing.JLabel EmailError;
    private javax.swing.JLabel HesloError;
    private javax.swing.JLabel MenoError;
    private javax.swing.JLabel PriezviskoError;
    private javax.swing.JTextField RegistraciaBydlisko;
    private javax.swing.JTextField RegistraciaBydliskoText;
    private javax.swing.JTextField RegistraciaEMail;
    private javax.swing.JTextField RegistraciaEMailText;
    private javax.swing.JTextField RegistraciaHeslo;
    private javax.swing.JPasswordField RegistraciaHesloText;
    private javax.swing.JTextField RegistraciaMeno;
    private javax.swing.JTextField RegistraciaMenoText;
    private javax.swing.JTextField RegistraciaPriezvisko;
    private javax.swing.JTextField RegistraciaPriezviskoText;
    private javax.swing.JTextField RegistraciaRegistracia;
    private javax.swing.JButton RegistraciaRegistrovat;
    private javax.swing.JTextField RegistraciaSkladOvocia;
    private javax.swing.JButton RegistraciaSpat;
    // End of variables declaration//GEN-END:variables
}
